### ISSUE TITLE
Data field types are not saved/rendered correctly

### ISSUE THREAD

**Issue by codepuncher** [dotmailer/dotmailer-wordpress-plugin#7]
The form fields in the DM_Widget are not output with the correct input types.

Instead of using the "type" property from the field Models, it is using `getName()` and saving that to the `dm_API_data_fields` option and it is not converted into the relevant `type="checkbox"` or other things. So on the front end, the form results in fields like `input[type="FIRSTNAME"]`.

**Comment by pvpcookie** [comment]
Hi @codepuncher 

Thank you for pointing this out i will look into it and let you know of any actions taken.

**Comment by codepuncher** [comment]
Thanks. Let me know if there is anything I can assist with. I also see lots of casing issues when setting up API credentials on a fresh install.

**Comment by codepuncher** [comment]
To help:

https://github.com/dotmailer/dotdigital-signup-form/blob/f0ee994d8a21025c1da18360d191121b2e4645e4/dm_widget.php#LL154C12-L154C12

The value passed to first argument of `writeFormLine()` is the value of `->getName()` from the dotdigital API Models rather than something like `boolean` or `string`

**Comment by sta1r** [comment]
OK, we're working on this and aiming to release a fix in w/c 19 June.

**Comment by codepuncher** [comment]
Brilliant, many thanks @sta1r!
Let me know if you need any testing done and I can help with that.

**Comment by sta1r** [comment]
@codepuncher I have code on https://github.com/dotmailer/dotdigital-signup-form/tree/AM/212887-data-field-types that we're preparing to release next week. Feel free to pull it down and give it a go locally. I haven't changed the version yet so it's still at 6.0.2.

**Comment by codepuncher** [comment]
Hi @sta1r, I've just tested and it works great.
Do you have a day set for the release yet?
Thanks

**Comment by sta1r** [comment]
Should be tomorrow.

**Comment by sta1r** [comment]
All released: https://en-gb.wordpress.org/plugins/dotmailer-sign-up-widget/. Thanks again for flagging this one!

**Comment by codepuncher** [comment]
Cheers @sta1r !

Have a great week.
